version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-nodejs-api
    environment:
       JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}
    env_file: .env
    ports:
      - "${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}"
    volumes:
      - .:/var/www
  db:
    image: mysql:5.7
    container_name: simple-nodejs-db
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    volumes:
      - simple-node-js-db:/var/lib/mysql
volumes:
  simple-node-js-db: